spring.application.name=spring-gift
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:wishlist;MODE=MYSQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

kakao.client-id=your-REST_API_KEY
kakao.redirect-uri=http://localhost:8080
kakao.authorize-url=https://kauth.kakao.com/oauth/authorize
kakao.token-url=https://kauth.kakao.com/oauth/token
kakao.user-info-url=https://kapi.kakao.com/v2/user/me
kakao.message-send-url=https://kapi.kakao.com/v2/api/talk/memo/default/send
